// Owner: S4 · Familial Risk & Clinical Approval — W.M.S.S.B. Wasala (IT24100559)
// Ownership is binding — do not edit this file if it is not yours. docs/OWNERSHIP.tsv
import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { Link, Navigate, useNavigate } from 'react-router-dom'

import { apiClient } from '../../services/apiClient'
import { useAppDispatch, useAppSelector } from '../../store/hooks'
import { registerDoctorUser } from '../../store/slices/authSlice'
import logoUrl from '../../assets/logo.png'

export function DoctorRegisterPage() {
  const dispatch = useAppDispatch()
  const navigate = useNavigate()
  const { isAuthenticated, user, status, error: authError } = useAppSelector((state) => state.auth)
  const [error, setError] = useState('')
  const [theme, setTheme] = useState<'light' | 'dark'>(() => {
    try {
      return (globalThis.localStorage?.getItem('fv-theme') as 'light' | 'dark') || 'light'
    } catch {
      return 'light'
    }
  })

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', theme)
  }, [theme])

  const setAppTheme = (nextTheme: 'light' | 'dark') => {
    setTheme(nextTheme)
    document.documentElement.setAttribute('data-theme', nextTheme)
    try {
      globalThis.localStorage?.setItem('fv-theme', nextTheme)
    } catch {
      // persistence is a convenience; ignore a blocked or unavailable store
    }
  }

  if (isAuthenticated) return <Navigate to={user?.role === 'DOCTOR' ? '/doctor-status' : '/dashboard'} replace />

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError('')
    const form = new FormData(event.currentTarget)
    const displayName = String(form.get('displayName') ?? '').trim()
    const email = String(form.get('email') ?? '').trim()
    const password = String(form.get('password') ?? '')
    const confirmPassword = String(form.get('confirmPassword') ?? '')
    const registrationNumber = String(form.get('registrationNumber') ?? '').trim()
    const specialty = String(form.get('specialty') ?? '').trim()
    const hospitalClinic = String(form.get('hospitalClinic') ?? '').trim()
    const phoneNumber = String(form.get('phoneNumber') ?? '').trim()

    if (!displayName) {
      setError('Please enter your Full Name.')
      return
    }
    if (!email || !email.includes('@') || !email.includes('.')) {
      setError('Please enter a valid Email address.')
      return
    }
    if (!password || password.length < 8) {
      setError('Password must be at least 8 characters long.')
      return
    }
    if (password !== confirmPassword) {
      setError('Password and Confirm Password do not match.')
      return
    }
    if (!registrationNumber || registrationNumber.length < 4) {
      setError('Please enter a valid Medical Registration No. (at least 4 characters).')
      return
    }
    if (!specialty) {
      setError('Please enter your Specialization.')
      return
    }
    if (!hospitalClinic) {
      setError('Please enter your Hospital / Clinic.')
      return
    }
    if (!phoneNumber || phoneNumber.length < 7) {
      setError('Please enter a valid Phone Number.')
      return
    }

    const registration = {
      displayName,
      email,
      password,
      registrationNumber,
      specialty,
      hospitalClinic,
      phoneNumber,
    }

    const result = await dispatch(registerDoctorUser(registration))
    if (!registerDoctorUser.fulfilled.match(result)) return

    try {
      await apiClient.post('/doctors/register', {
        registrationNumber,
        specialty,
        hospitalClinic,
        phoneNumber,
      })
    } catch {
      // Profile registration may already be created in single-step via /auth/register
    }
    navigate('/doctor-status', { replace: true })
  }

  return (
    <main className="login-page">
      {/* Top right clean theme toggle */}
      <div className="login-topbar">
        <div className="theme-toggle-group" role="group" aria-label="Theme mode switcher">
          <button
            type="button"
            className={`theme-toggle-btn ${theme === 'light' ? 'active' : ''}`}
            onClick={() => setAppTheme('light')}
          >
            <span aria-hidden="true">☀️</span> Light
          </button>
          <button
            type="button"
            className={`theme-toggle-btn ${theme === 'dark' ? 'active' : ''}`}
            onClick={() => setAppTheme('dark')}
          >
            <span aria-hidden="true">🌙</span> Dark
          </button>
        </div>
      </div>

      {/* Central Clinician Registration Stage */}
      <div className="login-stage">
        {/* Left floating live indicators */}
        <aside className="login-wing login-wing--left" aria-hidden="true">
          <div className="live-floating-card live-floating-card--1">
            <span className="live-icon-badge">🩺</span>
            <div>
              <strong>Clinical Queue</strong>
              <small><span className="pulse-dot" /> Triage review gate</small>
            </div>
          </div>
          <div className="live-floating-card live-floating-card--2">
            <span className="live-icon-badge">🔬</span>
            <div>
              <strong>Diagnostic Context</strong>
              <small>Multi-source extraction</small>
            </div>
          </div>
          <div className="live-floating-card live-floating-card--3">
            <span className="live-icon-badge">🛡️</span>
            <div>
              <strong>SLMC Verified</strong>
              <small>Strict compliance</small>
            </div>
          </div>
        </aside>

        {/* Clean centered expanded doctor registration card */}
        <div className="simple-login-card simple-login-card--wide">
          <div className="simple-login-brand">
            <img src={logoUrl} alt="Family Veda" width={56} height={56} />
            <h1>Family Veda</h1>
            <p>Clinician enrolment</p>
          </div>

          <p className="eyebrow">Synthetic clinician enrolment</p>
          <h2>Create doctor account</h2>
          <p className="muted">Clinical access remains blocked until an administrator verifies the profile. Never enter real medical credentials.</p>

          <form onSubmit={submit} className="register-form-grid" noValidate>
            <label className="field">
              <span>Full Name <strong style={{ color: 'var(--color-danger, #ef4444)' }}>*</strong></span>
              <input name="displayName" placeholder="e.g. Dr. Kasun Perera" required maxLength={120} />
            </label>

            <label className="field">
              <span>Email <strong style={{ color: 'var(--color-danger, #ef4444)' }}>*</strong></span>
              <input name="email" type="email" placeholder="doctor@example.invalid" required />
            </label>

            <label className="field">
              <span>Password <strong style={{ color: 'var(--color-danger, #ef4444)' }}>*</strong></span>
              <input name="password" type="password" placeholder="At least 8 characters" minLength={8} required />
            </label>

            <label className="field">
              <span>Confirm Password <strong style={{ color: 'var(--color-danger, #ef4444)' }}>*</strong></span>
              <input name="confirmPassword" type="password" placeholder="Re-enter password" minLength={8} required />
            </label>

            <label className="field">
              <span>Medical Registration No. <strong style={{ color: 'var(--color-danger, #ef4444)' }}>*</strong></span>
              <input name="registrationNumber" placeholder="e.g. SLMC-SYNTH-9941" minLength={4} maxLength={30} required />
            </label>

            <label className="field">
              <span>Specialization <strong style={{ color: 'var(--color-danger, #ef4444)' }}>*</strong></span>
              <select name="specialty" defaultValue="" required>
                <option value="" disabled>Select Specialization</option>
                <option value="General Practice / Family Medicine">General Practice / Family Medicine</option>
                <option value="Internal Medicine">Internal Medicine</option>
                <option value="Paediatrics">Paediatrics</option>
                <option value="Cardiology">Cardiology</option>
                <option value="Dermatology">Dermatology</option>
                <option value="Endocrinology & Diabetology">Endocrinology & Diabetology</option>
                <option value="Gastroenterology">Gastroenterology</option>
                <option value="Neurology">Neurology</option>
                <option value="Obstetrics & Gynaecology">Obstetrics & Gynaecology</option>
                <option value="Oncology">Oncology</option>
                <option value="Ophthalmology">Ophthalmology</option>
                <option value="Orthopaedic Surgery">Orthopaedic Surgery</option>
                <option value="Otolaryngology (ENT)">Otolaryngology (ENT)</option>
                <option value="Psychiatry">Psychiatry</option>
                <option value="Pulmonology / Respiratory Medicine">Pulmonology / Respiratory Medicine</option>
                <option value="General Surgery">General Surgery</option>
                <option value="Emergency Medicine">Emergency Medicine</option>
                <option value="Nephrology">Nephrology</option>
                <option value="Rheumatology">Rheumatology</option>
                <option value="Other Specialization">Other Specialization</option>
              </select>
            </label>

            <label className="field">
              <span>Hospital / Clinic <strong style={{ color: 'var(--color-danger, #ef4444)' }}>*</strong></span>
              <input name="hospitalClinic" placeholder="e.g. Colombo General Hospital / Family Clinic" maxLength={200} required />
            </label>

            <label className="field">
              <span>Phone Number <strong style={{ color: 'var(--color-danger, #ef4444)' }}>*</strong></span>
              <input name="phoneNumber" type="tel" placeholder="e.g. +94 77 123 4567" maxLength={50} required />
            </label>

            {(error || authError) && <p className="form-error field--full" role="alert">{error || authError}</p>}

            <button className="button button--primary button--full field--full" type="submit" disabled={status === 'loading'}>
              {status === 'loading' ? 'Creating doctor account…' : 'Register as Doctor'}
            </button>
          </form>

          <p className="privacy-note">Already registered? <Link to="/login">Return to sign in</Link></p>
          <p className="privacy-note">Need a family account instead? <Link to="/register">Register family</Link></p>
        </div>

        {/* Right floating live indicators */}
        <aside className="login-wing login-wing--right" aria-hidden="true">
          <div className="live-floating-card live-floating-card--4">
            <span className="live-icon-badge">⚖️</span>
            <div>
              <strong>Advisory Authorisation</strong>
              <small>Doctor approval required</small>
            </div>
          </div>
          <div className="live-floating-card live-floating-card--5">
            <span className="live-icon-badge">🧬</span>
            <div>
              <strong>Familial Risk Insights</strong>
              <small>Hereditary alerts</small>
            </div>
          </div>
          <div className="live-floating-card live-floating-card--6">
            <span className="live-icon-badge">⚡</span>
            <div>
              <strong>SLA Response Clock</strong>
              <small>Active monitoring</small>
            </div>
          </div>
        </aside>
      </div>
    </main>
  )
}

